name: Import Tasks to GitHub Projects

on:
  push:
    paths:
      - "project/tasks.md"
      - "data/example_report.md"

jobs:
  import_tasks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install requests
      - name: Run import script
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          GITHUB_PROJECT_ID: ${{ secrets.PROJECT_ID }}
        run: python src/github_projects.py